#!/usr/bin/env node
/**
 * Turns the TAP files produced by the suite scripts into execution records.
 *
 * Usage:
 *   node harness/automation/utilities/summarize.mjs <suite>     # refresh one suite's block
 *   node harness/automation/utilities/summarize.mjs --finalize  # write the run summary + archive
 *
 * Outputs (never hand-edited — always generated from real executions):
 *   harness/test-results/latest/summary.md
 *   harness/test-results/summaries/<RUN_ID>.md
 *   harness/test-results/historical/<RUN_ID>/             (copy of the TAP files)
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";

import { HARNESS_ROOT, RUN_ID, environmentSummary } from "./env.mjs";

const LATEST = `${HARNESS_ROOT}/test-results/latest`;
const SUMMARY = `${HARNESS_ROOT}/test-results/summaries`;
const HISTORY = `${HARNESS_ROOT}/test-results/historical/${RUN_ID}`;

const SUITE_ORDER = ["unit", "api", "ui", "performance", "security", "database"];

const parseTap = (file) => {
  const text = readFileSync(file, "utf8");
  const num = (label) => Number((text.match(new RegExp(`^# ${label} (\\d+)$`, "m")) ?? [])[1] ?? 0);

  const failing = [...text.matchAll(/^not ok \d+ - (.+?)(?: # TODO.*)?$/gm)]
    .map((m) => m[1].trim())
    .filter((name) => !name.includes("KNOWN ISSUE"));

  const knownIssues = [...text.matchAll(/^(?:ok|not ok) \d+ - (TC-\d+[a-z]? \| KNOWN ISSUE \([^)]+\): .+?)(?: # TODO.*)?$/gm)].map(
    (m) => m[1].trim(),
  );

  return {
    suite: file.split("/").pop().replace(/\.tap$/, ""),
    tests: num("tests"),
    pass: num("pass"),
    fail: num("fail"),
    todo: num("todo"),
    skipped: num("skipped"),
    cancelled: num("cancelled"),
    durationMs: Number((text.match(/^# duration_ms ([\d.]+)$/m) ?? [])[1] ?? 0),
    failing,
    knownIssues,
  };
};

const tapFiles = existsSync(LATEST)
  ? readdirSync(LATEST).filter((file) => file.endsWith(".tap"))
  : [];

if (tapFiles.length === 0) {
  console.error("[summarize] no TAP files found — run a suite first (npm run test:unit …)");
  process.exit(1);
}

const results = tapFiles.map((file) => parseTap(`${LATEST}/${file}`)).sort(
  (a, b) => SUITE_ORDER.indexOf(a.suite) - SUITE_ORDER.indexOf(b.suite),
);

const totals = results.reduce(
  (acc, r) => ({
    tests: acc.tests + r.tests,
    pass: acc.pass + r.pass,
    fail: acc.fail + r.fail,
    todo: acc.todo + r.todo,
    skipped: acc.skipped + r.skipped,
  }),
  { tests: 0, pass: 0, fail: 0, todo: 0, skipped: 0 },
);

const env = environmentSummary();
const passRate = totals.tests ? ((totals.pass / totals.tests) * 100).toFixed(1) : "0.0";

const md = `# Test execution summary — ${RUN_ID}

> Generated by \`harness/automation/utilities/summarize.mjs\` from TAP output. Do not hand-edit.

| Field | Value |
| --- | --- |
| Execution ID | ${RUN_ID} |
| Generated | ${new Date().toISOString()} |
| Target | ${env.baseUrl} |
| Node | ${env.node} (${env.platform}) |
| Suites recorded | ${results.length} of ${SUITE_ORDER.length} |

## Totals

| Total | Passed | Failed | Known issues (todo) | Skipped / Not executed |
| --- | --- | --- | --- | --- |
| ${totals.tests} | ${totals.pass} | ${totals.fail} | ${totals.todo} | ${totals.skipped} |

**Pass rate: ${passRate}%** (${totals.pass}/${totals.tests})

## Per suite

| Suite | Tests | Pass | Fail | Known issues | Skipped | Duration |
| --- | --- | --- | --- | --- | --- | --- |
${results.map((r) => `| ${r.suite} | ${r.tests} | ${r.pass} | ${r.fail} | ${r.todo} | ${r.skipped} | ${(r.durationMs / 1000).toFixed(2)}s |`).join("\n")}

## Failures

${results.flatMap((r) => r.failing.map((name) => `- **${r.suite}** · ${name}`)).join("\n") || "_None — every executed assertion passed._"}

## Known issues exercised (expected failures, tracked as bugs)

${results.flatMap((r) => r.knownIssues).length
  ? results.flatMap((r) => r.knownIssues.map((name) => `- ${name}`)).join("\n")
  : "_None recorded in this run._"}

## Artefacts

| Artefact | Location |
| --- | --- |
| Raw TAP | \`harness/test-results/latest/*.tap\` |
| Console logs | \`harness/evidence/logs/*-$RUN_ID.spec.txt\` |
| Server logs | \`harness/evidence/logs/server-*-$RUN_ID.log\` |
| Performance numbers | \`harness/test-results/latest/performance-summary.json\` |
| Archived run | \`harness/test-results/historical/${RUN_ID}/\` |
`;

writeFileSync(`${LATEST}/summary.md`, md);

if (process.argv.includes("--finalize")) {
  mkdirSync(HISTORY, { recursive: true });
  mkdirSync(SUMMARY, { recursive: true });
  for (const file of tapFiles) copyFileSync(`${LATEST}/${file}`, `${HISTORY}/${file}`);
  writeFileSync(`${SUMMARY}/${RUN_ID}.md`, md);
  console.log(`[summarize] ${RUN_ID}: ${totals.pass}/${totals.tests} passed, ${totals.fail} failed, ${totals.todo} known issues`);
  console.log(`[summarize] wrote ${SUMMARY}/${RUN_ID}.md and archived TAP to ${HISTORY}`);
} else {
  console.log(`[summarize] refreshed ${LATEST}/summary.md (${totals.pass}/${totals.tests} passed)`);
}
